// Hardcoded data for all pages — will be replaced with API calls later

export const CATEGORIES = [
  { id: 1, name: 'Fútbol', slug: 'futbol', icon: '⚽', count: 4200 },
  { id: 2, name: 'Motocross', slug: 'motocross', icon: '🏍️', count: 1800 },
  { id: 3, name: 'Básquet', slug: 'basquet', icon: '🏀', count: 950 },
  { id: 4, name: 'Rugby', slug: 'rugby', icon: '🏉', count: 620 },
  { id: 5, name: 'Ciclismo', slug: 'ciclismo', icon: '🚴', count: 430 },
  { id: 6, name: 'Casual', slug: 'casual', icon: '👕', count: 2100 },
  { id: 7, name: 'E-Sports', slug: 'esports', icon: '🎮', count: 780 },
  { id: 8, name: 'Voleibol', slug: 'voleibol', icon: '🏐', count: 320 },
];

export const DESIGNS = [
  {
    id: 1,
    name: 'Barcelona Champions 2026',
    slug: 'barcelona-champions-2026',
    description: 'Diseño inspirado en la camiseta del FC Barcelona campeón de La Liga 2026. Incluye patrones geométricos y degradados en azulgrana con detalles dorados.',
    pricePEN: 25.00,
    priceUSD: 6.50,
    compareAtPrice: 35.00,
    image: '/mockups/jersey_1.png',
    gallery: ['/mockups/jersey_1.png', '/mockups/jersey_2.png'],
    fileFormat: 'AI + PSD',
    categoryId: 1,
    category: { name: 'Fútbol', slug: 'futbol' },
    tags: [{ name: 'Barcelona', slug: 'barcelona' }, { name: 'Liga Española', slug: 'liga-espanola' }],
    isFeatured: true,
    isFree: false,
    downloadCount: 342,
    createdAt: '2026-05-10',
  },
  {
    id: 2,
    name: 'Guerrero Textura Grunge',
    slug: 'guerrero-textura-grunge',
    description: 'Jersey con efecto textura grunge agresivo. Ideal para equipos que buscan un look competitivo y moderno.',
    pricePEN: 18.00,
    priceUSD: 4.80,
    compareAtPrice: null,
    image: '/mockups/jersey_2.png',
    gallery: ['/mockups/jersey_2.png'],
    fileFormat: 'AI',
    categoryId: 1,
    category: { name: 'Fútbol', slug: 'futbol' },
    tags: [{ name: 'Grunge', slug: 'grunge' }, { name: 'Textura', slug: 'textura' }],
    isFeatured: true,
    isFree: false,
    downloadCount: 189,
    createdAt: '2026-05-08',
  },
  {
    id: 3,
    name: 'Galaxy Purple Edition',
    slug: 'galaxy-purple-edition',
    description: 'Diseño futurista con gradientes púrpura y patrones triangulares. Perfecto para equipos modernos.',
    pricePEN: 30.00,
    priceUSD: 8.00,
    compareAtPrice: 45.00,
    image: '/mockups/jersey_3.png',
    gallery: ['/mockups/jersey_3.png'],
    fileFormat: 'AI + PSD + SVG',
    categoryId: 7,
    category: { name: 'E-Sports', slug: 'esports' },
    tags: [{ name: 'Galaxy', slug: 'galaxy' }, { name: 'Futurista', slug: 'futurista' }],
    isFeatured: true,
    isFree: false,
    downloadCount: 521,
    createdAt: '2026-05-12',
  },
  {
    id: 4,
    name: 'Military Camo Pro',
    slug: 'military-camo-pro',
    description: 'Camiseta con camuflaje militar moderno en tonos verdes. Diseño agresivo para equipos de alto rendimiento.',
    pricePEN: 22.00,
    priceUSD: 5.80,
    compareAtPrice: null,
    image: '/mockups/jersey_4.png',
    gallery: ['/mockups/jersey_4.png'],
    fileFormat: 'AI',
    categoryId: 2,
    category: { name: 'Motocross', slug: 'motocross' },
    tags: [{ name: 'Camuflaje', slug: 'camuflaje' }, { name: 'Militar', slug: 'militar' }],
    isFeatured: true,
    isFree: false,
    downloadCount: 267,
    createdAt: '2026-05-09',
  },
  {
    id: 5,
    name: 'Flame Racing Orange',
    slug: 'flame-racing-orange',
    description: 'Jersey de motocross con patrón de llamas en naranja y negro. Diseño dinámico y agresivo.',
    pricePEN: 20.00,
    priceUSD: 5.30,
    compareAtPrice: 28.00,
    image: '/mockups/jersey_5.png',
    gallery: ['/mockups/jersey_5.png'],
    fileFormat: 'PSD',
    categoryId: 2,
    category: { name: 'Motocross', slug: 'motocross' },
    tags: [{ name: 'Racing', slug: 'racing' }, { name: 'Llamas', slug: 'llamas' }],
    isFeatured: false,
    isFree: false,
    downloadCount: 156,
    createdAt: '2026-05-07',
  },
  {
    id: 6,
    name: 'Retro Wave Pink',
    slug: 'retro-wave-pink',
    description: 'Diseño retro con olas de gradiente en azul navy y rosa. Estilo synthwave para los amantes de lo vintage.',
    pricePEN: 15.00,
    priceUSD: 4.00,
    compareAtPrice: null,
    image: '/mockups/jersey_6.png',
    gallery: ['/mockups/jersey_6.png'],
    fileFormat: 'AI + SVG',
    categoryId: 6,
    category: { name: 'Casual', slug: 'casual' },
    tags: [{ name: 'Retro', slug: 'retro' }, { name: 'Wave', slug: 'wave' }],
    isFeatured: false,
    isFree: false,
    downloadCount: 94,
    createdAt: '2026-05-06',
  },
  {
    id: 7,
    name: 'Argentina Concept 2026',
    slug: 'argentina-concept-2026',
    description: 'Concepto de la camiseta de Argentina para el Mundial 2026. Diseño moderno con detalles dorados.',
    pricePEN: 0,
    priceUSD: 0,
    compareAtPrice: null,
    image: '/mockups/jersey_1.png',
    gallery: ['/mockups/jersey_1.png'],
    fileFormat: 'AI',
    categoryId: 1,
    category: { name: 'Fútbol', slug: 'futbol' },
    tags: [{ name: 'Argentina', slug: 'argentina' }, { name: 'Selección', slug: 'seleccion' }],
    isFeatured: false,
    isFree: true,
    downloadCount: 1203,
    createdAt: '2026-05-11',
  },
  {
    id: 8,
    name: 'Chelsea Blackout Edition',
    slug: 'chelsea-blackout-edition',
    description: 'Versión blackout del Chelsea con patrones graffiti. Diseño urbano y moderno.',
    pricePEN: 28.00,
    priceUSD: 7.50,
    compareAtPrice: 40.00,
    image: '/mockups/jersey_2.png',
    gallery: ['/mockups/jersey_2.png'],
    fileFormat: 'AI + PSD',
    categoryId: 1,
    category: { name: 'Fútbol', slug: 'futbol' },
    tags: [{ name: 'Chelsea', slug: 'chelsea' }, { name: 'Blackout', slug: 'blackout' }],
    isFeatured: true,
    isFree: false,
    downloadCount: 412,
    createdAt: '2026-05-13',
  },
];

export const TAGS = [
  { id: 1, name: 'Barcelona', slug: 'barcelona' },
  { id: 2, name: 'Grunge', slug: 'grunge' },
  { id: 3, name: 'Galaxy', slug: 'galaxy' },
  { id: 4, name: 'Camuflaje', slug: 'camuflaje' },
  { id: 5, name: 'Racing', slug: 'racing' },
  { id: 6, name: 'Retro', slug: 'retro' },
  { id: 7, name: 'Argentina', slug: 'argentina' },
  { id: 8, name: 'Chelsea', slug: 'chelsea' },
  { id: 9, name: 'Futurista', slug: 'futurista' },
  { id: 10, name: 'Textura', slug: 'textura' },
];

export const PAYMENT_METHODS = [
  {
    id: 1,
    name: 'Yape',
    type: 'qr',
    icon: '📱',
    qrImage: null, // Will be an uploaded image
    details: 'Escanea el código QR con tu app de Yape y envía el monto exacto. Luego sube tu comprobante.',
    isActive: true,
  },
  {
    id: 2,
    name: 'PayPal',
    type: 'link',
    icon: '💳',
    linkUrl: 'https://paypal.me/ejemplo',
    details: 'Haz clic en el botón para ir a PayPal. Después de pagar, copia el ID de transacción.',
    isActive: true,
  },
];

export const ORDERS_MOCK = [
  {
    id: 1,
    orderCode: 'ORD-20260514-001',
    customerName: 'Carlos Mendoza',
    customerEmail: 'carlos@gmail.com',
    customerPhone: '+51 999888777',
    totalAmount: 43.00,
    paymentMethod: 'Yape',
    status: 'pending',
    createdAt: '2026-05-14 10:30',
    items: [
      { designName: 'Barcelona Champions 2026', unitPrice: 25.00 },
      { designName: 'Guerrero Textura Grunge', unitPrice: 18.00 },
    ],
  },
  {
    id: 2,
    orderCode: 'ORD-20260513-003',
    customerName: 'María López',
    customerEmail: 'maria@hotmail.com',
    customerPhone: null,
    totalAmount: 30.00,
    paymentMethod: 'PayPal',
    status: 'approved',
    createdAt: '2026-05-13 15:45',
    items: [
      { designName: 'Galaxy Purple Edition', unitPrice: 30.00 },
    ],
  },
  {
    id: 3,
    orderCode: 'ORD-20260512-007',
    customerName: 'Juan Pérez',
    customerEmail: 'juanp@yahoo.com',
    customerPhone: '+51 912345678',
    totalAmount: 22.00,
    paymentMethod: 'Yape',
    status: 'rejected',
    createdAt: '2026-05-12 09:15',
    items: [
      { designName: 'Military Camo Pro', unitPrice: 22.00 },
    ],
  },
  {
    id: 4,
    orderCode: 'ORD-20260514-002',
    customerName: 'Ana Torres',
    customerEmail: 'ana.t@gmail.com',
    customerPhone: '+51 987654321',
    totalAmount: 48.00,
    paymentMethod: 'Yape',
    status: 'pending',
    createdAt: '2026-05-14 11:20',
    items: [
      { designName: 'Flame Racing Orange', unitPrice: 20.00 },
      { designName: 'Chelsea Blackout Edition', unitPrice: 28.00 },
    ],
  },
];
